# name: C/C++ CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure --with-compat --add-dynamic-module=dynamic/ModSecurity
#     - name: make
#       run: make
#     - name: make modules
#       run: make modules
#     - name: make install
#       run: make install
